default: &default
  adapter: postgresql
  encondig: 'unicode'
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: shortener
  username: <%= ENV['DB_USER'] || ENV['USER'] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 }.to_i * 2 %>

development:
  <<: *default
  database: shortener_development

test:
  <<: *default
  database: shortener_test

staging:
  <<: *default
  password: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  password: <%= ENV['DATABASE_URL'] %>
